### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ahmdhjj** [ahmdhjj/django-pythonanywhere#12]
- [x] Setup a new ssh key, and copy & paste it into the account's authorised keys (#11)
- [x] Set up a virtualenv (#8)
- [x] Set environment variables like SECRET_KEY in PA (#29)
- [ ] Add info about consoles (limit of 2 consoles, how API call does not actually start the process (connecting to it in a browser will do that)(#13)
- [x] #32
- [x] #33

**Comment by ahmdhjj** [comment]
Some important help pages to gather info from:

- [ ]  [Integrating a development environment with PythonAnywhere](https://help.pythonanywhere.com/pages/IntegratingWithPythonAnywhere/)
- [x]  [How to set environment variables for your web apps (for SECRET_KEY etc)](https://help.pythonanywhere.com/pages/environment-variables-for-web-apps/)
- [x]  [How to use a virtualenv in your web app (to get newer versions of django, flask etc)](https://help.pythonanywhere.com/pages/Virtualenvs/)
- [x]  [Deploying an existing Django project on PythonAnywhere](https://help.pythonanywhere.com/pages/DeployExistingDjangoProject/)
- [x] [How to setup static files in Django](https://help.pythonanywhere.com/pages/DjangoStaticFiles/)

**Comment by ahmdhjj** [comment]
Closing in favour of #13
